version: '3.7'
services:
  backup_data: #Dump Data Only
    container_name: backup_data
    image: deividdy/mysql-bk-s3-ftp:latest
    environment:
      MYSQLDUMP_OPTIONS: "--default-character-set=utf8 --single-transaction=TRUE --routines --events --no-create-info=TRUE"
      MYSQLDUMP_DATABASE: bulla_dfe
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: root

      S3_ACCESS_KEY_ID: ""
      S3_SECRET_ACCESS_KEY: ""
      S3_BUCKET: ""
      S3_PREFIX: backup
      S3_REGION: "us-east-1"

      FTP_USER: root
      FTP_PASS: root
      FTP_HOST: localhost:30000
      FTP_PATH: backup

  backup_struct: #Dump Struct Only
    container_name: backup_struct
    image: deividdy/mysql-bk-s3-ftp:latest
    environment:
      MYSQLDUMP_OPTIONS: "--default-character-set=utf8 --single-transaction=TRUE --no-data --skip-triggers"
      MYSQLDUMP_DATABASE: bulla_dfe
      MYSQL_HOST: "mysql-srv"
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: root

      S3_ACCESS_KEY_ID: ""
      S3_SECRET_ACCESS_KEY: ""
      S3_BUCKET: ""
      S3_PREFIX: backup
      S3_REGION: "us-east-1"

      FTP_USER: root
      FTP_PASS: root
      FTP_HOST: localhost:30000
      FTP_PATH: backup